sudo: required

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  pip: true
  directories:
    - node_modules

install:
  - yarn global add gulp-cli
  - yarn install

script: gulp

deploy:
  on:
    branch: master
  provider: s3
  # Use environment variables
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  # Name of the S3 Bucket
  bucket: dan.salvagni.io
  skip_cleanup: true
  local_dir: build
